resource_group_name = "dev-testrg34"
resource_group_location = "West Europe"
virtual_network_name = "dev-vnet1"
address_space = ["10.0.0.0/16"]
subnet_name = "dev-subnet1"
address_prefix = "10.0.1.0/24"
managed_disk_name = "dev-disk1"
create_option = "Empty"
storage_account_type = "Standard_LRS"
disk_size_gb = 4
